### ISSUE TITLE
Update create market form to include ui for liquidity, and remove no longer needed 

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur-ui-react-components#12]
The create market form can be opened using the "make a market" button:

![image](https://cloud.githubusercontent.com/assets/118814/15528663/ef7bc6c4-2213-11e6-813a-be6a04db897b.png)

The "additional market info" page has some elements that are no longer needed, confirm with jack whcih ones need to be removed/changed/added:

![image](https://cloud.githubusercontent.com/assets/118814/15528689/1bbce4a2-2214-11e6-939e-dab243373479.png)

Also, some new ui has to be added somewhere to ask the user how much initial liquidity they want to provide, and in what distribution. Ask joey/jack for details on that.

The first part of this issue is researching what the specific requirements are, posted in a comment here, so we can discuss as a team how to proceed.

**Comment by stephensprinkle** [comment]
![create markets - mmer modal](https://cloud.githubusercontent.com/assets/287003/15621788/453f88b0-2418-11e6-9830-875c8a2df7c0.png)
![trading interface](https://cloud.githubusercontent.com/assets/287003/15621794/51154b70-2418-11e6-98d2-b26e57bc02e2.png)

**Comment by stephensprinkle** [comment]
TODO:
* Remove Links  
* Add makerFees

**Comment by stephensprinkle** [comment]
Started work on this issue.

**Comment by stephensprinkle** [comment]
Notable fields to exclude: 'constant b`, `orders per side`, `current fair price`, `partial fill`

**Comment by stephensprinkle** [comment]
Additional notes: 

a couple of these things in the UI are using confusing terms:

[11:45] 
 ```Liquidity - $1000
Initial fair price for [x,y,z] outcomes - $.30, $.40, $.30
Starting quantity [depth/volume @ x price] - 20
Size of best bid/offer - 30
Price width - $.04
Price depth [distance between orders] - $.05
```
(edited)

[11:45] 
liquidity - self explanatory, fair price - also good

[11:45] 
size of best bid/offer - also good

[11:46] 
starting quantity is a bit confusing b/c we also have price depth

[11:46] 
starting quantity is actually the ​_amount of shares_​ at each order down the book / a given price point

[11:46] 
price width is a solid term --- width between the initial best bid/ask (edited)

[11:47] 
price depth is kinda confusing with starting quantity b/c someone may think depth means amount of shares at a given location

[11:48] 
price depth is really just the distance between orders or the price delta between two orders on the same side

[11:48] 
i.e. .18 and .13 is .05, .13 and .08 is .5, etc

[11:49] 
`Starting quantity` -> Shares per order   and `Price depth` -> Distance between orders may be clearer, dunno

**Comment by stephensprinkle** [comment]
PRs #668 + #33 resolve this issue -- closing.
