### ISSUE TITLE
Research non-fb based iframed id-oriented (not account) comment system or use FB

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur-ui-react-components#15]
The disqus implementation we have has two problems:

1. it doesn't run in an iframe opening a vector for attack
2. it is based on an owned augur account in their system

We need a comment solution that uses iframes, and manages conversations based on a provided id, not an account or page url (because ipfs urls will change on version updates)

If after some quick research nothing obvious pops up, implement the facebook comment system (as long as it is confirmed the above is true)

**Comment by stephensprinkle** [comment]
After discussion, needs additional investigation of alternatives.

**Comment by stephensprinkle** [comment]
TODO:

- [ ] Ensure FB comments fulfills requirements (Fails due to lack of iFrame support)
- [ ] Investigate Alternatives

**Comment by joeykrug** [comment]
FB comments support iframes

**Comment by joeykrug** [comment]
http://stackoverflow.com/questions/16446465/facebook-comment-plugin-does-not-show-in-iframe

http://jsfiddle.net/onigetoc/bgeswf0g/

**Comment by stephensprinkle** [comment]
Ah, I stand corrected -- I was basing that assertion on the FB docs indicating that iFrames was not supported: [FB Comments Configurator](https://developers.facebook.com/docs/plugins/comments#configurator)

**Comment by joeykrug** [comment]
Ah must not be "officially" supported or something but still works - got it

**Comment by stephensprinkle** [comment]
Per discussion this morning on our team call, removing from MVP milestone.
