### ISSUE TITLE
Implement disqus commenting system on market details page

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur-ui-react-components#2]
Some suggestions:

- meta comment widget that aloows sign-in to various commenting systems like disqus, fb, etc.

- disqus alone might be less confusing and more usable, but all part of the investigation of this ticket

- some other competing service

Once we agree on a service, we will want to implement it in the ui, tied to market.id, and display in the /market view (market-page.jsx) in all states except reporting

**Comment by joeykrug** [comment]
Discus itself allows sign-in with Facebook, Twitter, and gmail - don't need to make it any more complicated than that imo for now

**Comment by stephensprinkle** [comment]
Closing per this PR #11
