### ISSUE TITLE
Maker's share entered as proportion but has percent symbol

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-ui-react-components#25]
![screenshot - 06152016 - 03 41 41 pm](https://cloud.githubusercontent.com/assets/2637020/16099929/d5bcef76-330f-11e6-8130-db4068ed4879.png)

Probably better to have them enter it as a percent (since trading fee is entered that way)!

**Comment by stephensprinkle** [comment]
Updated the default maker fee to 50%.

This resolved in a PR over in the augur repo #636.
