### ISSUE TITLE
Design account page

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-ui-react-components#32]

**Comment by thinkloop** [comment]
- display user's handle or shortened id, if handle not available, in site-header, to reach the account section

- provide sign out link in top-right of black area on account page

subsection 1
- display user's full id and ability to reveal their private key, and ability to export account, ex:
      - handle: JohnnyD [edit]
      - id: 1XDAGFFDSGF&GVDSHRYY$FFBHDGEWR 
      - .......................... [reveal private key]
      - [download my account]
