### ISSUE TITLE
Create Market: Replace "trading fee" with "taker fee" and re-define "maker fee"

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur-ui-react-components#36]
More details here: https://github.com/AugurProject/augur/issues/670

In short, need to change the labels and descriptions of the fees, as well as the numerical constraints (passed in from augur).

**Comment by stephensprinkle** [comment]
PR #42 + Augur [#675](https://github.com/AugurProject/augur/pull/675) resolve this issue -- closing.
