### ISSUE TITLE
Implement phase 1 limit/orderbook trading

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur-ui-react-components#4]
Trading is moving to be limit and order-book based. An initial implementation exists commented in the code. Bring back this implementation, including bids/asks views, completing and fixing any missing or broken pieces.

**Comment by thinkloop** [comment]
- under "top bids" and "top asks" show `[numShares] @ [price]`

- when clicking into inputs in a row, show additional bids/asks and rename column headers to simply "bids" and "asks"

- ensure that clicking in different boxes in the same row does not toggle the additional bids/asks on and off

- fix trade summary formatting and style

**Comment by stephensprinkle** [comment]
Simply converting above comment to task list --

- [ ] under "top bids" and "top asks" show [numShares] @ [price]

- [ ] when clicking into inputs in a row, show additional bids/asks and rename column headers to simply "bids" and "asks"

- [ ] ensure that clicking in different boxes in the same row does not toggle the additional bids/asks on and off

- [ ] fix trade summary formatting and style (add dummy handlers so it shows and hides appropriately)

**Comment by stephensprinkle** [comment]
PR's #52 + [#620](https://github.com/AugurProject/augur/pull/690) should resolve this issue.  

I'll wait until they are merged down to close.

**Comment by stephensprinkle** [comment]
Post PR Refinements --

- [ ] Refine Render Method Style 

- [ ] Componentize the rows of trade-panel-body

- [ ] map -> forEach where applicable

- [ ] Move `<tfoot>` below body

**Comment by stephensprinkle** [comment]
PRs [#696](https://github.com/AugurProject/augur/pull/696) in Augur + #56 in AURC resolve this issue + additional change request...closing.
