### ISSUE TITLE
Don't include assertions in build

### ISSUE THREAD

**Issue by priecint** [AugurProject/augur-ui-react-components#62]
`assertions` are only used in augur tests so there is no need to send them to browser (i.e. bundle them with [UI components](https://github.com/AugurProject/augur-ui-react-components/blob/master/src/components.jsx#L23)).

Instead of
`import { assertions } from 'augur-ui-react-components';`
we can have something like
`import assertions from 'augur-ui-react-components/lib/assertions';`

**Comment by priecint** [comment]
I think the correct way how to deal with this is:
1/ add `build:assertions` script to package.json which builds `src/assertions` to `lib/assertions` - this would be later used in augur tests
2/ remove assertions from `components.jsx`

**Comment by tinybike** [comment]
Bumped to top priority (see https://github.com/AugurProject/augur/pull/714 for explanation).

**Comment by tinybike** [comment]
Removing this from MVP as it does not solve the npm link problem.
