### ISSUE TITLE
Mysterious 0 appears in navbar when logged out

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-ui-react-components#63]
![screenshot - 07212016 - 07 34 37 pm](https://cloud.githubusercontent.com/assets/2637020/17076137/6f497dd2-505f-11e6-8df0-d5b85061496a.png)

**Comment by JohnDanz** [comment]
Seems to be resolved, doesn't appear to be an issue with the UI but something that was getting passed down from higher up in the stack. On the latest master build in the augur repo the 0 appears to be gone.
