### ISSUE TITLE
Add checkbox for generating an order book during market creation

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-ui-react-components#76]
Right now, generating an initial order book is a required part of market creation.  It should be decoupled so that it is available, but not required.  Suggested way of doing this is to add a checkbox somewhere in the create market process:

 - [x] Set up initial buy/sell orders for this market

If checked, the generateOrderBook form appears.  If unchecked, then the market is created without automatically calling `augur.generateOrderBook`.

**Comment by stephensprinkle** [comment]
PR's #77 + [#727](https://github.com/AugurProject/augur/pull/727) resolve this issue -- closing.
