### ISSUE TITLE
Figure out and setup architecture for shared selector tests to be able to communicate and test selectors in both repos

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur-ui-react-components#8]
Per last meeting, the leading strategy so far is to create selector tests inside the ui repo that test the shape of the selector, then build another similar test in the augur repo that transforms state into the selector then runs the ui selector to test its shape. We don't want to duplicate any portion of these tests. Let's see if we can implement this nicely.

Once we nail down the strategy we should move the relevant test portions from the augur repo to the ui repo.

**Comment by JohnDanz** [comment]
Looks like we can take advantage of `npm explore` command to achieve the depency script running.

Augur could have a command called "test:ui" which would call a specific test that uses a fake state to keep passing selectors to this repo's selector test. An example of the plan would be like so:

AUGUR REPO:
`npm explore augur-ui-react-components -- npm run test`

this will run the `test` script in augur-ui-react-components. We need a way to have the augur-ui-react-components test use selectors from the Augur repo. Originally I planned to simply pass a path to find the selectors but I don't know if the test script in the UI repo will allow us to go completely out of the containing package. My assumption will be that it will not as this could be considered a security concern.
