### ISSUE TITLE
React error when navigating from market detail page to markets listing

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-ui-react-components#81]
If I'm on a market's detail page and then go to the main markets listing, I get the following error:
```
components.jsx:15: Uncaught Invariant Violation: Minified React error #34; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=34 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
If you follow that link, the full error message is:
```
React DOM tree root should always have a node reference.
```
This happens on both https://augur-dev.firebaseapp.com as well as on the latest augur+AURC master branches.

**Comment by tinybike** [comment]
Forgot to add: this error is only thrown once, and afterward, the main markets listing loads successfully.

**Comment by tinybike** [comment]
Fixed, thank god

**Comment by tinybike** [comment]
Correction: not fixed :/

**Comment by JohnDanz** [comment]
So this error will throw numerous times, and it apparently can be recreated by navigating to a single market page, then going to any other page, not just markets.

**Comment by JohnDanz** [comment]
Fixed the issue, the culprit was an onClick event on the marketPage. We shouldn't assign things to the top level element in the app (first element inside of <div id="app" >) to avoid this type of issue in the future.
